# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

textspace_help <- function(type = "help") {
    invisible(.Call('_ruimtehol_textspace_help', PACKAGE = 'ruimtehol', type))
}

textspace_args <- function(textspacemodel) {
    .Call('_ruimtehol_textspace_args', PACKAGE = 'ruimtehol', textspacemodel)
}

textspace <- function(model = "textspace.bin", save = FALSE, trainFile = "", initModel = "", validationFile = "", testFile = "", basedoc = "", predictionFile = "", fileFormat = "fastText", label = "__label__", loss = "hinge", similarity = "cosine", lr = 0.01, termLr = 1e-9, norm = 1.0, margin = 0.05, initRandSd = 0.001, p = 0.5, dropoutLHS = 0.0, dropoutRHS = 0.0, wordWeight = 0.5, dim = 100L, epoch = 5L, ws = 5L, maxTrainTime = 60*60*24*100L, validationPatience = 10L, thread = 1L, maxNegSamples = 10L, negSearchLimit = 50L, minCount = 1L, minCountLabel = 1L, bucket = 100000L, ngrams = 1L, trainMode = 0L, K = 5L, batchSize = 5L, verbose = FALSE, debug = FALSE, adagrad = TRUE, normalizeText = FALSE, saveEveryEpoch = FALSE, saveTempModel = FALSE, shareEmb = TRUE, useWeight = FALSE, trainWord = FALSE, excludeLHS = FALSE, embeddings = matrix(0, 100), embeddings_bucket_size = 0L) {
    .Call('_ruimtehol_textspace', PACKAGE = 'ruimtehol', model, save, trainFile, initModel, validationFile, testFile, basedoc, predictionFile, fileFormat, label, loss, similarity, lr, termLr, norm, margin, initRandSd, p, dropoutLHS, dropoutRHS, wordWeight, dim, epoch, ws, maxTrainTime, validationPatience, thread, maxNegSamples, negSearchLimit, minCount, minCountLabel, bucket, ngrams, trainMode, K, batchSize, verbose, debug, adagrad, normalizeText, saveEveryEpoch, saveTempModel, shareEmb, useWeight, trainWord, excludeLHS, embeddings, embeddings_bucket_size)
}

textspace_evaluate <- function(textspacemodel, testFile = "", basedoc = "", predictionFile = "", K = 5L) {
    .Call('_ruimtehol_textspace_evaluate', PACKAGE = 'ruimtehol', textspacemodel, testFile, basedoc, predictionFile, K)
}

textspace_load_model <- function(file_model, is_tsv = FALSE) {
    .Call('_ruimtehol_textspace_load_model', PACKAGE = 'ruimtehol', file_model, is_tsv)
}

textspace_save_model <- function(textspacemodel, file, as_tsv = FALSE) {
    .Call('_ruimtehol_textspace_save_model', PACKAGE = 'ruimtehol', textspacemodel, file, as_tsv)
}

textspace_dictionary <- function(textspacemodel) {
    .Call('_ruimtehol_textspace_dictionary', PACKAGE = 'ruimtehol', textspacemodel)
}

textspace_embedding_doc <- function(textspacemodel, x) {
    .Call('_ruimtehol_textspace_embedding_doc', PACKAGE = 'ruimtehol', textspacemodel, x)
}

textspace_embedding_ngram <- function(textspacemodel, x) {
    .Call('_ruimtehol_textspace_embedding_ngram', PACKAGE = 'ruimtehol', textspacemodel, x)
}

textspace_embedding_lhsrhs <- function(textspacemodel, type = "lhs") {
    .Call('_ruimtehol_textspace_embedding_lhsrhs', PACKAGE = 'ruimtehol', textspacemodel, type)
}

textspace_predict <- function(textspacemodel, input, k = 5L, basedoc = "", sep = " ") {
    .Call('_ruimtehol_textspace_predict', PACKAGE = 'ruimtehol', textspacemodel, input, k, basedoc, sep)
}

textspace_knn <- function(textspacemodel, line, k) {
    .Call('_ruimtehol_textspace_knn', PACKAGE = 'ruimtehol', textspacemodel, line, k)
}

